language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy

script:
  - cargo check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
  - echo "{\"a\":4}" | cargo run '"a"'
  - |
    cargo run -q -- '"one".[2:0],"two","three"' <<EOF
    {
    "one": [1, 2, 3],
    "two": 2,
    "three": 3
    }
    EOF

after_success:
  - ./after-success.sh
