[package]
authors = ["Davy Duperron <yamafaktory@gmail.com>"]
categories = ["command-line-utilities"]
description = "A JSON query language CLI tool"
edition = "2018"
exclude = [".travis.yml", "after-success.sh", "benches/**/*", "rustfmt.toml"]
keywords = ["CLI", "JSON", "tool"]
license = "MIT"
name = "jql"
readme = "README.md"
repository = "https://github.com/yamafaktory/jql"
version = "2.3.4"

[badges]
travis-ci = { repository = "yamafaktory/jql" }

[dev-dependencies]
criterion = "0.2"

[dependencies]
clap = "2.32.0"
colored_json = "1"
lazy_static = "1.2.0"
pest = "2.1.0"
pest_derive = "2.1.0"
rayon = "1.0.3"

[dependencies.serde_json]
version = "1.0.34"
default-features = false
features = ["preserve_order"]

[[bench]]
name = "benchmark"
harness = false

[lib]
name = "jql"
path = "src/lib.rs"

[[bin]]
name = "jql"
path = "src/bin.rs"
