[package]
authors = ["Davy Duperron <yamafaktory@gmail.com>"]
categories = ["command-line-utilities"]
description = "A JSON query language CLI tool"
keywords = ["CLI", "JSON", "tool"]
license = "MIT"
name = "jql"
readme = "README.md"
repository = "https://github.com/yamafaktory/jql"
version = "1.0.1"

[badges]
travis-ci = { repository = "yamafaktory/jql" }

[dependencies]
clap = "2.32.0"
lazy_static = "1.2.0"
pest = "2.0.2"
pest_derive = "2.0.1"
rayon = "1.0.3"
regex= "1.1.0"
serde_json = "1.0.33"
