name: performance

on:
  push:
    branches:
    - master
  schedule:
    - cron: "00 01 * * *"

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Install hyperfine and jql - jq is already available!
        run: cargo install hyperfine && cargo install jql
      - name: Run performance benchmarks
        run: ./performance.sh
      - name: Commit directly to master branch
        run: |
          git config --global user.name 'yamafaktory'
          git config --global user.email 'yamafaktory@gmail.com'
          git commit -a -F- <<EOF
          chore(performance): update benchmarks - [skip ci]


          skip-checks: true
          EOF
          git push
